name = "erkankoyun-contact"
main = "src/index.js"
compatibility_date = "2026-02-17"

[vars]
ALLOWED_ORIGIN = "https://erkankoyun.com"
TO_EMAIL = "erkankoyun@outlook.com"
FROM_EMAIL = "noreply@erkankoyun.com"
FROM_NAME = "ErkanKoyun.com Contact"
# Turnstile kullanacaksan sonra dolduracağız:
TURNSTILE_SECRET = ""
